package com.mircea.botez.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mircea.botez.model.User;
import com.mircea.botez.model.CyclingActivity;

import com.mircea.botez.model.UserDao;
import com.mircea.botez.model.CyclingActivityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig cyclingActivityDaoConfig;

    private final UserDao userDao;
    private final CyclingActivityDao cyclingActivityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        cyclingActivityDaoConfig = daoConfigMap.get(CyclingActivityDao.class).clone();
        cyclingActivityDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        cyclingActivityDao = new CyclingActivityDao(cyclingActivityDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(CyclingActivity.class, cyclingActivityDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        cyclingActivityDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public CyclingActivityDao getCyclingActivityDao() {
        return cyclingActivityDao;
    }

}
